
try{
    console.log(x);
}
catch(err){
    console.log(err);
}
finally{
    console.log("This akways execute");
}

console.log("You have reached the end!")